### ISSUE TITLE
Error when deploying

### ISSUE THREAD

**Issue by davistan** [AndyGrom/node-deploy-server#7]
Hi Andy, thanks for creating this system. As we are testing it, we found this problem as below:

```
deploy
choose target configuration number:
[1] development: http://localhost:15478
[2] staging: http://192.168.10.252:15478
target 2
deploy to: http://192.168.10.252:15478
authenticate...
pack...
deploy...
ERROR:
{ [Error: socket hang up] code: 'ECONNRESET' }
```

Is there any detailed logs or area that we know why it fails?

**Comment by AndyGrom** [comment]
Try to manually start the deploy server from cosole and see its output.
From /server/ folder do this: node ./lib/server.js

**Comment by davistan** [comment]
here's the log as below (from the receiving side)

```
root@58f6e90907f3:/# /usr/local/bin/node /usr/local/lib/node_modules/node-deploy-server/lib/server.js
connect.multipart() will be removed in connect 3.0
visit https://github.com/senchalabs/connect/wiki/Connect-3.0 for alternatives
connect.limit() will be removed in connect 3.0
current dir is: /usr/local/lib/node_modules/node-deploy-server
node deploy server launched on port: 15478
GET / 302 13ms - 56b
GET /login 200 15ms - 4.37kb
GET /favicon.ico 404 3ms
GET /favicon.ico 404 1ms
POST /login 302 11ms - 46b
GET / 200 7ms - 1.33kb
GET /api/settings 200 4ms - 155b
GET /api/serverSettings 200 2ms - 133b
GET /api/serverSettings 200 2ms - 133b
GET /api/settings 200 2ms - 155b
POST /login 302 5ms - 23b
Error: Request aborted
    at IncomingMessage.onReqAborted (/usr/local/lib/node_modules/node-deploy-server/node_modules/express/node_modules/connect/node_modules/multiparty/index.js:131:17)
    at emitNone (events.js:67:13)
    at IncomingMessage.emit (events.js:166:7)
    at abortIncoming (_http_server.js:266:11)
    at Socket.serverSocketCloseListener (_http_server.js:279:5)
    at emitOne (events.js:82:20)
    at Socket.emit (events.js:169:7)
    at TCP._onclose (net.js:469:12)
POST /deploy/db-node 400 120007ms - 485b
```

**Comment by AndyGrom** [comment]
Thank you for your bug report. I will reproduce it.
